---
title: "Ensemble classifier"
author: "Lisa"
date: "29/06/2021"
output: html_document
---
```{r}
require(readr)
require(stringr)
require(dplyr)
require(magrittr)
```

Specify paths
```{r}
mlplasmids_path <- "../../mlplasmids_bac/results/mlplasmids_all_results.tsv"
platon_path <- "../../platon_bac/results/platon_all_results.csv"
plascope_path <- "../../plascope_bac/results/plascope_all_results.csv"
rfplasmid_path <- "../../rfplasmid_bac/results/rfplasmid_predictions/prediction.csv"

output_path <- "../results/EC_result_all_contigs2.csv"
```


Import output of individual classifiers

Mlplasmids
```{r,message=FALSE}
mlplasmids_out <- read_tsv(mlplasmids_path)
names(mlplasmids_out)<-c('assembly_accession','sra_accession','prob_chromosome','prob_plasmid','prediction','contig_name','contig_length')
mlplasmids_out$prediction %<>% tolower()
mlplasmids_out %<>% mutate(mlplasmids=prediction) %>% select(contig_name,mlplasmids)
```

Platon
```{r}
platon_out <- read.csv(platon_path, header = FALSE)
names(platon_out) <- c("contig_name","prediction")
platon_out %<>% mutate(contig_name=str_replace(contig_name,'>',''))
platon_out %<>% rename(platon=prediction)
```

PlaScope
For PlaScope, 'unclassified' predictions are changed to 'chromosome'.
```{r}
plascope_out <- read.csv(plascope_path, header = FALSE)
names(plascope_out) <- c("contig_name","prediction")
plascope_out %<>% mutate(contig_name=str_replace(contig_name,'>',''))
plascope_out %<>% mutate(prediction=ifelse(prediction=="unclassified","chromosome",prediction))
plascope_out %<>% rename(plascope=prediction)
```

RFPlasmid
```{r}
rfplasmid_out <- read.csv(rfplasmid_path)
names(rfplasmid_out) <- c("short_name","prediction","votes_chromosome","votes_plasmid","contig_name")
rfplasmid_out$prediction[rfplasmid_out$prediction=="c"]<- "chromosome"
rfplasmid_out$prediction[rfplasmid_out$prediction=="p"]<- "plasmid"
rfplasmid_out %<>% rename(rfplasmid=prediction) %>% select(contig_name,rfplasmid)
```

Merge the outputs (choose ensemble here)
```{r,message=FALSE}
all_output <- full_join(full_join(platon_out,plascope_out),mlplasmids_out)
all_output %<>% mutate(final_result=ifelse(str_count(paste(platon,plascope,mlplasmids),"plasmid")>1,"plasmid","chromosome"))
EC_result <- all_output %>% select(contig_name,final_result)
```

Write to file
```{r}
write.csv(EC_result,output_path,row.names = FALSE)
```

